version: '3.8'

services:
  duty-mongo:
    image: mongo:5.0
    container_name: duty-mongo
    restart: always
    ports:
      - 27180:27017
    volumes:
      - ./data/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/mongodb/mongod.conf:/etc/mongod.conf
      - ./data/mongodb/data/db/:/data/db
    env_file:
      - .env

  duty-chapter:
    image: bietdoikiem/duty-chapter:1.0
    container_name: duty-chapter
    restart: unless-stopped
    ports:
      - 4000:4000
    env_file:
      - .env

networks:
  default:
    external:
      name: thenewsquest-network
