version: '3.8'

services:
  duty-db:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - 27180:27017
    volumes:
      - ./data/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/mongodb/mongod.conf:/etc/mongod.conf
      - ./data/mongodb/data/db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=duty
      - MONGO_INITDB_USERNAME=duty-admin
      - MONGO_INITDB_PASSWORD=duty-admin
